t = int(input("Введите число t: "))
v = int(input("ВВедите число v: "))
x = int(input("Введите число x: "))
y = int(input("Введите число y: "))
print(f'а) 5 10   б) 100 {t}   в) {x} 25')
print(f'   7 см     1949 {v}     {x} {y}')
