a = int(input("Введите число t: "))
b = int(input("ВВедите число v: "))
x = int(input("Введите число x: "))
y = int(input("Введите число y: "))
print(f'а) 2 кг   б) {a} 1  в) {x} {y}')
print(f'   13 17     19 {b}    5 {y}')